docs: $(wildcard apertium-platform-doc/*)
	raco pkg install --name apertium-platform-doc; raco setup -p apertium-platform-doc; cp -r doc/index/*.html ../; cp -r doc/index/*.svg ../; cp -r doc/index/*.png ../; cp -r doc/index/*.css ../
